version: 2

sources:
  - name: public
    database: NAYA_DBT  # your actual database
    schema: PUBLIC
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
